### ISSUE TITLE
Move to Github dependabot?

### ISSUE THREAD

**Issue by pmelab** [AmazeeLabs/gatsby-starter-amazee#151]
Since dependabot has been bought by Github, should we switch to their version of it? With the configuration in `.github/dependabot.yml`? Are there any downsides to this?

**Comment by dan2k3k4** [comment]
I believe they will eventually remove Dependabot v1 so we would need to migrate to v2 (Github hosted).

The downsides would be that we would need a Github Action workflow to auto-merge the PRs if they are "good."

Our current configuration is set up for updating `packages.json` dependencies with:

```
update_configs:
- allowed_updates:
  - match:
      update_type: security
      dependency_type: development
  - match:
      update_type: security
      dependency_type: production
  directory: "/"
  package_manager: javascript
  target_branch: development
  update_schedule: monthly
```

In addition, the following defaults have been applied to this config by Dependabot:
```
automerged_updates: []
default_assignees: []
default_labels:
- dependencies
default_reviewers: []
ignored_updates: []
version_requirement_updates: auto
```
